# Generated by Django 4.0.4 on 2023-07-19 04:21

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=certificate.models.certificate_pdf_upload_path),
        ),
    ]
